### ISSUE TITLE
Fix Tooltip Position

### ISSUE THREAD

**Issue by curran** [unhcr/dataviz-population-change#2]
![image](https://user-images.githubusercontent.com/68416/29022318-7c6ec7e4-7b86-11e7-95f4-7a72431801d4.png)
Chrome

**Comment by LuisSevillano** [comment]
Hi everyone, congrats for this nice project 
I was think it would be better to use `event.clientY` instead `event.pageY` for tooltip position. ClientY/clientY are relative to the upper left edge of the content area of the browser window. This point does not move even if the user moves a scrollbar from within the browser.
Fixed in #55 
Thanks
